name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Grant Execution Permission to gradlew
      run: chmod +x gradlew

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' 
        distribution: 'temurin' 
        cache: 'gradle'

    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest

    - name: Build with Gradle
      # Este paso es importante para descargar dependencias y preparar el proyecto
      run: ./gradlew build --no-daemon

    - name: Run Cucumber/Selenium Tests
      # Ejecuta la tarea 'test' de Gradle. Esto generar√° los reportes (JUnit XML/Cucumber JSON)
      run: ./gradlew test --no-daemon

   # add before this step: uses: actions/setup-node@v4 (see below)
    - name: Upload Test Results to Qase (via npx)
      run: |
        echo "Starting Qase CLI upload..."
        # npx will fetch and run the correct package in one step
        npx --yes qaseio upload junit "build/test-results/test/TEST-*.xml"
      env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
          QASE_PROJECT_CODE: FRT
          QASE_RUN_NAME: Automated Tests Execution from GitHub Actions - ${{ github.sha }}
          QASE_ENVIRONMENT: CI-Github-Actions
      

   